import type { Metadata } from "next";
import Searchbar from "@/components/searchbar";
import Footer from "@/components/footer";
import Footer2 from "@/components/footer2";
import Menubar from "@/components/menubar";
import Topnav from "@/components/topnav";
import '../global.css'



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Topnav/>
        <Searchbar/>
        {children}
        <Footer/>
        <Footer2/>
        <Menubar/>
        
      </body>
    </html>
  );
}
